-- Generated by nwg-displays on 2026-09-17 at 15:15:27. Do not edit manually.

hl.monitor({
    output = "desc:Eizo Nanao Corporation EV3285 0x03BB5AC9",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.25,
    vrr = 0
})
